# puzzle_trainer.py
# PyQt5 chess puzzle trainer integrating your ChessBoard widget.
# Requires: python-chess, PyQt5
#
# Run: python puzzle_trainer.py

from __future__ import annotations

import re
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import pyqtSignal, QObject

import chess
import chess.pgn
from io import StringIO

# Import your board widget
from chessboard import ChessBoard

import sys
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, Union, Tuple


# ---------- Data structures ----------


# Each puzzle becomes normalized to:
#   start_fen: str
#   line_uci: List[str]  (expected sequence, includes both sides)
@dataclass
class Puzzle:
    start_fen: str
    line_uci: List[str]
    title: str = ""


# ---------- Puzzler engine (signals-first) ----------


class Puzzler(QObject):
    """
    Puzzler: validates moves against a pre-defined expected line.
    Accepts inputs as (FEN, moves) or PGN strings. Emits signals
    to keep the UI decoupled from puzzle logic.

    Conventions:
      * User plays the side indicated by start_fen side-to-move.
      * Opponent replies (odd indices from expected line) are auto-played.
    """

    puzzleChanged = pyqtSignal(str, dict)  # fen, info
    moveResult = pyqtSignal(bool, str, dict)  # correct, fen, info
    scoreChanged = pyqtSignal(int, int)  # correct_count, failed_count
    hintAvailable = pyqtSignal(str, int, int)  # uci, from_sq, to_sq

    def __init__(
        self,
        raw_puzzles: List[Union[Tuple[str, Union[str, List[str]]], str]],
        parent=None,
    ):
        super().__init__(parent)
        self._puzzles: List[Puzzle] = self._parse_puzzles(raw_puzzles)
        self.total_puzzles = len(self._puzzles)
        self._idx: int = 0
        self._board_truth: chess.Board = chess.Board()
        self._expected: List[str] = []
        self._user_color: bool = chess.WHITE
        self._autoplaying: bool = False

        # simple score model (can be extended with weights, streaks, time, etc.)
        self.correct_count = 0
        self.failed_count = 0

        if self._puzzles:
            self._load_puzzle(0)

    # ---------- Public API ----------

    def next_puzzle(self):
        if not self._puzzles:
            return
        self._idx = (self._idx + 1) % len(self._puzzles)
        self._load_puzzle(self._idx)

    def retry_puzzle(self):
        if not self._puzzles:
            return
        self._load_puzzle(self._idx)

    @QtCore.pyqtSlot(str)
    def check_move(self, played_uci: str):
        """
        Validate a user move. This should be connected to ChessBoard.moveMade (str uci).
        If wrong, emit moveResult(False, fen, info). If correct, pop and possibly
        autoplay opponent reply moves, then emit result.
        """
        if self._autoplaying:
            # Ignore moveMade signals generated by our own autoplay
            return

        info = {
            "puzzle_index": self._idx + 1,
            "total_puzzles": len(self._puzzles),
            "played": played_uci,
            "expected": self._expected[0] if self._expected else None,
            "remaining": len(self._expected),
            "solved": False,
            "message": "",
        }

        if not self._expected:
            info["message"] = "No expected moves remain; puzzle already finished."
            self.moveResult.emit(True, self._board_truth.fen(), info)
            return

        expected_uci = self._expected[0]

        if played_uci == expected_uci:
            # Accept and advance
            move = chess.Move.from_uci(played_uci)
            if move not in self._board_truth.legal_moves:
                # Shouldn't happen, but guard anyway if UI board was desynced
                info["message"] = (
                    "Move matched expected UCI but was illegal in truth board."
                )
                self.failed_count += 1
                self.scoreChanged.emit(self.correct_count, self.failed_count)
                self.moveResult.emit(False, self._board_truth.fen(), info)
                return

            # Apply to truth board and pop expectation
            self._board_truth.push(move)
            self._expected.pop(0)

            # If opponent is to move next, autoplay as long as expected remains and
            # it's not user to move.
            self._maybe_autoplay_opponent()

            # Check solved
            if not self._expected:
                self.correct_count += 1
                info["solved"] = True
                info["message"] = "Puzzle solved!"
                self.scoreChanged.emit(self.correct_count, self.failed_count)
                self.moveResult.emit(True, self._board_truth.fen(), info)
            else:
                info["message"] = "Correct."
                self.moveResult.emit(True, self._board_truth.fen(), info)

        else:
            # Wrong move
            self.failed_count += 1
            info["message"] = "Wrong move."
            self.scoreChanged.emit(self.correct_count, self.failed_count)
            # Do not change truth board; UI can undo the last move to stay in sync
            self.moveResult.emit(False, self._board_truth.fen(), info)

    def request_hint(self):
        """Emit the next user move as a hint (arrow)."""
        if not self._expected:
            return
        next_uci = self._expected[0]
        move = chess.Move.from_uci(next_uci)
        self.hintAvailable.emit(next_uci, move.from_square, move.to_square)

    # ---------- Internals ----------

    def _load_puzzle(self, idx: int):
        puzzle = self._puzzles[idx]
        self._board_truth = chess.Board(puzzle.start_fen)
        self._expected = list(puzzle.line_uci)  # copy
        self._user_color = self._board_truth.turn

        info = {
            "puzzle_index": idx + 1,
            "total_puzzles": len(self._puzzles),
            "title": puzzle.title or f"Puzzle {idx+1}",
            "user_color": "White" if self._user_color == chess.WHITE else "Black",
            "total_moves_in_line": len(self._expected),
        }

        self.puzzleChanged.emit(self._board_truth.fen(), info)

        # If first to move is opponent (edge case if line starts with reply), autoplay
        self._maybe_autoplay_opponent()

    def _maybe_autoplay_opponent(self):
        """Autoplay all pending opponent replies from expected line."""
        if not self._expected:
            return

        # Play while it's opponent's turn and there are moves left
        self._autoplaying = True
        try:
            while self._expected and self._board_truth.turn != self._user_color:
                next_reply_uci = self._expected[0]
                reply_move = chess.Move.from_uci(next_reply_uci)

                if reply_move not in self._board_truth.legal_moves:
                    # Defensive: stop autoplay if something is inconsistent
                    break

                # Push to truth board and pop from expected
                self._board_truth.push(reply_move)
                self._expected.pop(0)

                # UI board will animate via ChessBoard.apply_move() in MainWindow.
                # We ONLY change the truth board here; UI board will be instructed to mirror.
                # Emitting moveResult here is optional; we keep things quiet for now.
        finally:
            self._autoplaying = False

    # ---------- Parsing utilities ----------

    def _parse_puzzles(
        self, raw: List[Union[Tuple[str, Union[str, List[str]]], str]]
    ) -> List[Puzzle]:
        out: List[Puzzle] = []
        for item in raw:
            if isinstance(item, tuple) and len(item) == 2:
                fen, moves = item
                fen = (fen or "").strip()
                if not fen:
                    continue
                line_uci = self._to_uci_line_from_fen_and_moves(fen, moves)
                out.append(Puzzle(start_fen=fen, line_uci=line_uci, title="FEN puzzle"))
            elif isinstance(item, str):
                # treat as PGN string
                parsed = self._parse_pgn_to_puzzle(item)
                if parsed:
                    out.append(parsed)
        return out

    def _to_uci_line_from_fen_and_moves(
        self, fen: str, moves: Union[str, List[str]]
    ) -> List[str]:
        brd = chess.Board(fen)
        tokens: List[str]
        if isinstance(moves, str):
            # Split by whitespace, strip move numbers like "1.", "2." if present
            raw = moves.strip()
            tokens = [t for t in re.split(r"\s+", raw) if t]
        else:
            tokens = list(moves)

        uci_line: List[str] = []
        for tok in tokens:
            # Skip move numbers and result markers
            if re.match(r"^\d+\.+$", tok) or tok in ("*", "1-0", "0-1", "1/2-1/2"):
                continue

            # Try SAN first, then UCI
            move_obj: Optional[chess.Move] = None
            try:
                move_obj = brd.parse_san(tok)
            except ValueError:
                # Try UCI
                try:
                    move_obj = chess.Move.from_uci(tok)
                    if move_obj not in brd.legal_moves:
                        raise ValueError
                except Exception:
                    raise ValueError(f"Unrecognized move token '{tok}' for FEN:\n{fen}")

            # Normalize to UCI, push
            uci_line.append(move_obj.uci())
            brd.push(move_obj)
        return uci_line

    def _parse_pgn_to_puzzle(self, pgn_str: str) -> Optional[Puzzle]:
        try:
            game = chess.pgn.read_game(StringIO(pgn_str))
            if game is None:
                return None
            brd = game.board()  # initial position (respects FEN in headers if present)
            start_fen = brd.fen()
            line_uci: List[str] = []
            for mv in game.mainline_moves():
                line_uci.append(mv.uci())
                brd.push(mv)
            title = game.headers.get("Event", "PGN puzzle")
            return Puzzle(start_fen=start_fen, line_uci=line_uci, title=title)
        except Exception:
            return None


# ---- Session data containers -------------------------------------------------


@dataclass
class PuzzleRecord:
    index: Optional[int] = None  # 1-based puzzle index if available
    title: Optional[str] = None
    outcome: str = ""  # "solved" | "failed"
    played: Optional[str] = None  # user's last move (uci/san)
    expected: Optional[str] = None  # expected move if failed


@dataclass
class SessionResults:
    mode: str = "Free"  # "Free" | "Timed"
    total_seconds: int = 0
    elapsed_seconds: int = 0
    solved: int = 0
    failed: int = 0
    attempted: int = 0
    records: List[PuzzleRecord] = field(default_factory=list)


# ---- Main Window -------------------------------------------------------------


class MainWindow(QtWidgets.QMainWindow):
    """
    Chess puzzle trainer MainWindow with Free and Timed modes.
    - Does NOT modify your Puzzler class.
    - Wires up ChessBoard <-> Puzzler and adds session/timer UI.
    """

    def __init__(self, puzzler: Puzzler, parent=None):
        super().__init__(parent)
        self.puzzler = puzzler

        # --- state ---
        self.session_active: bool = False
        self.session_mode: str = "Free"  # "Free" | "Timed"
        self.remaining_seconds: int = 0
        self.total_seconds: int = 0
        self.results = SessionResults()

        # track if we are between puzzles to avoid double counts
        self._waiting_next_after_result: bool = False

        # --- timers ---
        self.countdown_timer = QtCore.QTimer(self)
        self.countdown_timer.setInterval(1000)  # 1 sec
        self.countdown_timer.timeout.connect(self._on_tick)

        # --- UI ---
        self._build_ui()
        self._wire_signals()

        # Initial cosmetic state
        self._set_timer_visible(False)
        self._set_controls_enabled(free_mode=True)

    # ------------------------- UI Construction --------------------------------

    def _build_ui(self):
        self.setWindowTitle("Chess Puzzle Trainer — Free / Timed")
        self.resize(980, 720)

        central = QtWidgets.QWidget(self)
        self.setCentralWidget(central)
        root = QtWidgets.QHBoxLayout(central)
        root.setContentsMargins(12, 12, 12, 12)
        root.setSpacing(12)

        # Left: board
        self.board = ChessBoard(size=600)
        root.addWidget(self.board, stretch=2)

        # Right: sidebar controls/info
        sidebar = QtWidgets.QVBoxLayout()
        sidebar.setSpacing(10)
        root.addLayout(sidebar, stretch=1)

        # Mode + Duration row
        mode_row = QtWidgets.QHBoxLayout()
        sidebar.addLayout(mode_row)

        mode_row.addWidget(QtWidgets.QLabel("Mode:"))
        self.cmb_mode = QtWidgets.QComboBox()
        self.cmb_mode.addItems(["Free", "Timed"])
        mode_row.addWidget(self.cmb_mode, stretch=1)

        self.lbl_time = QtWidgets.QLabel("Seconds:")
        mode_row.addWidget(self.lbl_time)
        self.spin_seconds = QtWidgets.QSpinBox()
        self.spin_seconds.setRange(10, 3600)  # 10s .. 60m
        self.spin_seconds.setSingleStep(10)
        self.spin_seconds.setValue(120)  # default 2 minutes
        mode_row.addWidget(self.spin_seconds)

        self.btn_start = QtWidgets.QPushButton("Start")
        self.btn_start.setCursor(QtCore.Qt.PointingHandCursor)
        mode_row.addWidget(self.btn_start)

        # Big timer display
        self.lbl_timer = QtWidgets.QLabel("00:00")
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_timer.setStyleSheet("color:#1f2937")  # neutral
        sidebar.addWidget(self.lbl_timer)

        # Puzzle title + status
        self.lbl_title = QtWidgets.QLabel("—")
        self.lbl_title.setWordWrap(True)
        self.lbl_title.setStyleSheet("font-weight: 600; font-size: 16px;")
        sidebar.addWidget(self.lbl_title)

        self.lbl_status = QtWidgets.QLabel("Ready.")
        self.lbl_status.setWordWrap(True)
        self.lbl_status.setStyleSheet("color:#374151;")
        sidebar.addWidget(self.lbl_status)

        # Score
        self.lbl_score = QtWidgets.QLabel("Solved: 0   Failed: 0   Attempted: 0")
        sidebar.addWidget(self.lbl_score)

        # Action buttons
        btn_row = QtWidgets.QHBoxLayout()
        sidebar.addLayout(btn_row)

        self.btn_retry = QtWidgets.QPushButton("Retry ↺")
        self.btn_retry.setCursor(QtCore.Qt.PointingHandCursor)
        btn_row.addWidget(self.btn_retry)

        self.btn_next = QtWidgets.QPushButton("Next ▶")
        self.btn_next.setCursor(QtCore.Qt.PointingHandCursor)
        btn_row.addWidget(self.btn_next)

        self.btn_hint = QtWidgets.QPushButton("Hint 💡")
        self.btn_hint.setCursor(QtCore.Qt.PointingHandCursor)
        btn_row.addWidget(self.btn_hint)

        sidebar.addStretch(1)

        # Footer
        self.lbl_footer = QtWidgets.QLabel(
            "Timed session auto-advances on solve or wrong move."
        )
        self.lbl_footer.setStyleSheet("color:#6b7280; font-size:12px;")
        sidebar.addWidget(self.lbl_footer)

    def _wire_signals(self):
        # Board -> Puzzler
        self.board.moveMade.connect(self._on_user_move)

        # Puzzler -> UI
        # TODO: If your signal names differ, replace below accordingly.
        self.puzzler.puzzleChanged.connect(self._on_puzzle_changed)
        self.puzzler.moveResult.connect(self._on_move_result)

        # Buttons
        self.btn_start.clicked.connect(self._on_start_clicked)
        self.btn_next.clicked.connect(self._on_next_clicked)
        self.btn_retry.clicked.connect(self._on_retry_clicked)
        self.btn_hint.clicked.connect(self._on_hint_clicked)

        # Mode changes
        self.cmb_mode.currentTextChanged.connect(self._on_mode_changed)

    # ----------------------------- Event Handlers -----------------------------

    @QtCore.pyqtSlot()
    def _on_start_clicked(self):
        mode = self.cmb_mode.currentText()
        if mode == "Timed":
            self._start_timed_session()
        else:
            self._start_free_session()

    def _start_free_session(self):
        # No timer; enable manual controls
        self.session_mode = "Free"
        self.session_active = True
        self._set_timer_visible(False)
        self._set_controls_enabled(free_mode=True)
        self._reset_results(keep_mode=True, seconds=0)
        self.lbl_status.setText("Free mode: solve at your own pace.")
        # Optional: move to the first puzzle if needed

    def _start_timed_session(self):
        self.session_mode = "Timed"
        self.remaining_seconds = int(self.spin_seconds.value())
        self.total_seconds = self.remaining_seconds
        self._reset_results(keep_mode=True, seconds=self.total_seconds)

        self._set_timer_visible(True)
        self._update_timer_label()

        # Lock mode/duration, lock manual next/retry; hint optional (disabled here)
        self._set_controls_enabled(free_mode=False)

        # Start timer
        self.session_active = True
        self.countdown_timer.start()
        self.lbl_status.setText("Timed mode started. Good luck!")
        # Ensure we are on a puzzle; if your puzzler needs a kick, uncomment:
        # self.puzzler.next_puzzle()

    def _on_mode_changed(self, text: str):
        # Only influencing visibility before session starts
        if not self.session_active:
            timed = text == "Timed"
            self.lbl_time.setEnabled(timed)
            self.spin_seconds.setEnabled(timed)
            self._set_timer_visible(False)

    @QtCore.pyqtSlot()
    def _on_next_clicked(self):
        # Manual Next only in Free mode
        if self.session_mode == "Free":
            self.puzzler.next_puzzle()

    @QtCore.pyqtSlot()
    def _on_retry_clicked(self):
        # Retry current puzzle (if Puzzler provides it)
        if self.session_mode == "Free":
            if hasattr(self.puzzler, "retry_puzzle"):
                self.puzzler.retry_puzzle()
            else:
                # Fallback: just reload current via next->previous if you track index outside
                self.lbl_status.setText("Retry not available in this build of Puzzler.")

    @QtCore.pyqtSlot()
    def _on_hint_clicked(self):
        if hasattr(self.puzzler, "request_hint"):
            self.puzzler.request_hint()
        else:
            self.lbl_status.setText("Hint not available in this build of Puzzler.")

    @QtCore.pyqtSlot(str)
    def _on_user_move(self, uci: str):
        # Board finished applying user move; ask Puzzler to judge
        if hasattr(self.puzzler, "check_move"):
            self.puzzler.check_move(uci)

    @QtCore.pyqtSlot(str, dict)
    def _on_puzzle_changed(self, fen: str, info: Dict[str, Any]):
        # Orient board side if info contains color; otherwise keep current
        self.board.update_board(fen)

        # Title and index
        idx = info.get("puzzle_index")
        total = info.get("total_puzzles")
        title = info.get("title") or "Puzzle"
        hdr = f"{title}"
        if idx and total:
            hdr += f"  ({idx}/{total})"
        self.lbl_title.setText(hdr)

        # Give the board focus so user can move immediately
        self.board.setFocus()

    @QtCore.pyqtSlot(bool, str, dict)
    def _on_move_result(self, correct: bool, fen: str, info: Dict[str, Any]):
        """
        Timed:
          - wrong -> count failed, auto-next
          - solved -> count solved, auto-next
          - correct but not solved -> continue same puzzle
        Free:
          - just show feedback; user controls Next/Retry
        """
        # Always sync board with truth position received
        self.board.update_board(fen)

        # Pretty feedback
        if correct:
            self.lbl_status.setStyleSheet("color:#166534;")  # green-700
            msg = "Correct"
        else:
            self.lbl_status.setStyleSheet("color:#991b1b;")  # red-800
            msg = "Wrong"

        # Enrich message with details if provided
        played = info.get("played")
        expected = info.get("expected")
        if not correct and expected:
            msg += f" — expected {expected}"
        elif played:
            msg += f" — played {played}"
        self.lbl_status.setText(msg)

        # Free mode: done
        if self.session_mode == "Free":
            return

        # Timed mode: auto-advance policy
        if not self.session_active:
            return  # session may have ended on tick

        # Avoid double-next if we’re already scheduling one
        if self._waiting_next_after_result:
            return

        # Determine outcome for counting
        solved = bool(info.get("solved"))
        remaining = info.get("remaining")
        if correct and (solved or remaining == 0):
            self._count_outcome("solved", info)
            self._schedule_auto_next()
        elif not correct:
            self._count_outcome("failed", info)
            self._schedule_auto_next()
        else:
            # still in the same (multi-move) puzzle
            pass

    # ------------------------------- Timer ------------------------------------

    def _on_tick(self):
        # End session if time runs out
        if self.remaining_seconds > 0:
            self.remaining_seconds -= 1
            self._update_timer_label()

        # Check if all puzzles are finished
        puzzles_finished = False
        # Option 1: If you track attempted vs total
        if self.results.attempted >= self.puzzler.total_puzzles:
            puzzles_finished = True
        # Option 2: If Puzzler exposes is_finished
        # if getattr(self.puzzler, "is_finished", False):
        #     puzzles_finished = True

        if self.remaining_seconds <= 0 or puzzles_finished:
            self._finish_session()

    def _update_timer_label(self):
        mm = self.remaining_seconds // 60
        ss = self.remaining_seconds % 60
        self.lbl_timer.setText(f"{mm:02d}:{ss:02d}")
        # color cue: last 10 seconds red
        color = "#1f2937" if self.remaining_seconds > 10 else "#b91c1c"
        self.lbl_timer.setStyleSheet(f"color:{color}")

    # ----------------------------- Session Logic ------------------------------

    def _reset_results(self, keep_mode: bool = True, seconds: int = 0):
        self.results = SessionResults(
            mode=self.session_mode if keep_mode else "Free",
            total_seconds=seconds,
            elapsed_seconds=0,
            solved=0,
            failed=0,
            attempted=0,
            records=[],
        )
        self._render_score()

    def _count_outcome(self, outcome: str, info: Dict[str, Any]):
        # outcome: "solved" | "failed"
        rec = PuzzleRecord(
            index=info.get("puzzle_index"),
            title=info.get("title"),
            outcome=outcome,
            played=info.get("played"),
            expected=info.get("expected"),
        )
        self.results.records.append(rec)
        if outcome == "solved":
            self.results.solved += 1
        elif outcome == "failed":
            self.results.failed += 1
        self.results.attempted = self.results.solved + self.results.failed
        self._render_score()

    def _schedule_auto_next(self):
        # short delay to let user see feedback
        self._waiting_next_after_result = True
        QtCore.QTimer.singleShot(350, self._do_auto_next)

    def _do_auto_next(self):
        self._waiting_next_after_result = False
        if self.session_active:
            self.puzzler.next_puzzle()

    def _finish_session(self):
        if not self.session_active:
            return
        self.session_active = False
        self.countdown_timer.stop()

        self.results.elapsed_seconds = (
            self.results.total_seconds - self.remaining_seconds
        )
        self.remaining_seconds = 0
        self._update_timer_label()

        # Freeze inputs
        self.board.setDisabled(True)
        self._set_controls_enabled(free_mode=True, during_summary=True)

        # Summary dialog
        self._show_summary_dialog()

    def _show_summary_dialog(self):
        solved = self.results.solved
        failed = self.results.failed
        attempted = self.results.attempted
        mm = self.results.elapsed_seconds // 60
        ss = self.results.elapsed_seconds % 60

        text = (
            f"<h3>Session complete</h3>"
            f"<p><b>Mode:</b> {self.results.mode}<br>"
            f"<b>Time used:</b> {mm:02d}:{ss:02d}<br>"
            f"<b>Solved:</b> {solved} &nbsp;&nbsp; "
            f"<b>Failed:</b> {failed} &nbsp;&nbsp; "
            f"<b>Attempted:</b> {attempted}</p>"
        )
        msg = QtWidgets.QMessageBox(self)
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setWindowTitle("Summary")
        msg.setTextFormat(QtCore.Qt.RichText)
        msg.setText(text)
        msg.addButton("OK", QtWidgets.QMessageBox.AcceptRole)
        msg.exec_()

        # Re-enable board for subsequent free play
        self.board.setDisabled(False)
        self.lbl_status.setText(
            "Session complete. You can start a new session or switch to Free mode."
        )

    # Public: you can call this to save to DB later
    def get_session_results(self) -> SessionResults:
        return self.results

    # --------------------------- UI Helpers -----------------------------------

    def _set_timer_visible(self, visible: bool):
        self.lbl_timer.setVisible(visible)

    def _set_controls_enabled(self, free_mode: bool, during_summary: bool = False):
        """Enable/disable UI affordances depending on mode."""
        if free_mode:
            # Free or after summary
            self.cmb_mode.setEnabled(True)
            self.spin_seconds.setEnabled(self.cmb_mode.currentText() == "Timed")
            self.btn_start.setEnabled(True)

            # In free: manual navigation allowed
            self.btn_next.setEnabled(True)
            self.btn_retry.setEnabled(True)
            self.btn_hint.setEnabled(True)
        else:
            # Timed session running: lock mode, duration, and manual nav
            self.cmb_mode.setEnabled(False)
            self.spin_seconds.setEnabled(False)
            self.btn_start.setEnabled(False)

            self.btn_next.setEnabled(False)
            self.btn_retry.setEnabled(False)
            # Optional: disable hints in timed sessions to keep scoring clean
            self.btn_hint.setEnabled(False)

        # When just finished, keep Start enabled so user can start again
        if during_summary:
            self.btn_start.setEnabled(True)

    def _render_score(self):
        self.lbl_score.setText(
            f"Solved: {self.results.solved}   "
            f"Failed: {self.results.failed}   "
            f"Attempted: {self.results.attempted}"
        )


def build_example_puzzles() -> List[Union[Tuple[str, Union[str, List[str]]], str]]:
    """
    Demonstration inputs. Replace with your own sets.
    - One FEN-based line (moves are SAN)
    - One PGN-based line
    """
    # FEN + SAN/UCIs
    fen_1 = chess.STARTING_FEN
    moves_1 = "e2e4 e7e5 g1f3 b8c6 f1b5"  # legal, shows user+opponent turns

    # PGN: the starting FEN is implicit; mainline is extracted
    pgn_1 = """[Event "Training"]
[Site "Local"]
[Date "2025.09.10"]
[Round "-"]
[White "You"]
[Black "Bot"]
[Result "*"]

1. d4 d5 2. c4 e6 3. Nc3 *
"""

    return [
        (fen_1, moves_1),
        pgn_1,
    ]


# ---------- main ----------


def main():
    app = QtWidgets.QApplication(sys.argv)

    puzzles = build_example_puzzles()
    puzzler = Puzzler(puzzles)

    win = MainWindow(puzzler)
    win.show()

    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
